version: "3"

services:
  app-db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data/:/docker-entrypoint-initdb.d

  # Dashboard DB Container
  dashboard:
    container_name: phpmyadmin2
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "18081:80"
    depends_on:
      - app-db
    environment:
      - "PMA_HOST=app-db"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./server:/app
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
      - /app/node_modules # <---- this enables a much faster start/reload
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading
    depends_on:
      - server
    networks:
      - app-network
    command: npm run dev

volumes:
  app_db_volume:


networks:
  app-network:
    driver: bridge
